#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                            ------------------------                              #
#                            PosCommands Configuration                             #
#                                 By Loving11ish                                   #
#                            ------------------------                              #
#                            --[mc.crapticraft.com]--                              #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#This is for the first block combination
#This sets the combination of blocks that the player walks over to trigger the commands.
Top-Trigger-Block-1: OAK_PRESSURE_PLATE
Bottom-Trigger-Block-1: BEDROCK

#This sets a location that the player can be sent once they trigger the commands.
#This is useful if you wish the player to be moved away from the trigger to prevent spamming.
1-TP-Enabled: false
1-TP-Once-Triggered-X: 0
1-TP-Once-Triggered-Y: 100
1-TP-Once-Triggered-Z: 0

#These commands are triggered when a player walks over the blocks set above (the '/' is not required).
#Enter the commands below, up to 4 commands can be triggered simultaneously.
#All commands are executed by the player not the console, therefore the players must have the relevant permissions assigned.
1-Command-1-enabled: true
1-Command-1: 'kit starter'

1-Command-2-enabled: false
1-Command-2: 'enjin points'

1-Command-3-enabled: false
1-Command-3: 'warp spawn'

1-Command-4-enabled: false
1-Command-4: ''

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#This is for a second block combination.
#This sets the combination of blocks that the player walks over to trigger the commands.
Top-Trigger-Block-2: STONE_PRESSURE_PLATE
Bottom-Trigger-Block-2: REDSTONE_BLOCK

#This sets a location that the player can be sent once they trigger the commands.
#This is useful if you wish the player to be moved away from the trigger to prevent spamming.
2-TP-Enabled: false
2-TP-Once-Triggered-X: 0
2-TP-Once-Triggered-Y: 100
2-TP-Once-Triggered-Z: 0

#These commands are triggered when a player walks over the blocks set above (the '/' is not required).
#Enter the commands below, up to 4 commands can be triggered simultaneously.
#All commands are executed by the player not the console, therefore the players must have the relevant permissions assigned.
2-Command-1-enabled: false
2-Command-1: 'rules'

2-Command-2-enabled: false
2-Command-2: ''

2-Command-3-enabled: false
2-Command-3: ''

2-Command-4-enabled: false
2-Command-4: ''

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#This is for a third block combination.
#This sets the combination of blocks that the player walks over to trigger the commands.
Top-Trigger-Block-3: SPRUCE_PRESSURE_PLATE
Bottom-Trigger-Block-3: OBSIDIAN

#This sets a location that the player can be sent once they trigger the commands.
#This is useful if you wish the player to be moved away from the trigger to prevent spamming.
3-TP-Enabled: false
3-TP-Once-Triggered-X: 0
3-TP-Once-Triggered-Y: 100
3-TP-Once-Triggered-Z: 0

#These commands are triggered when a player walks over the blocks set above (the '/' is not required).
#Enter the commands below, up to 4 commands can be triggered simultaneously.
#All commands are executed by the player not the console, therefore the players must have the relevant permissions assigned.
3-Command-1-enabled: false
3-Command-1: ''

3-Command-2-enabled: false
3-Command-2: ''

3-Command-3-enabled: false
3-Command-3: ''

3-Command-4-enabled: false
3-Command-4: ''

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#This is for a forth block combination.
#This sets the combination of blocks that the player walks over to trigger the commands.
Top-Trigger-Block-4: DARK_OAK_PRESSURE_PLATE
Bottom-Trigger-Block-4: SPRUCE_LOG

#This sets a location that the player can be sent once they trigger the commands.
#This is useful if you wish the player to be moved away from the trigger to prevent spamming.
4-TP-Enabled: false
4-TP-Once-Triggered-X: 0
4-TP-Once-Triggered-Y: 100
4-TP-Once-Triggered-Z: 0

#These commands are triggered when a player walks over the blocks set above (the '/' is not required).
#Enter the commands below, up to 4 commands can be triggered simultaneously.
#All commands are executed by the player not the console, therefore the players must have the relevant permissions assigned.
4-Command-1-enabled: false
4-Command-1: ''

4-Command-2-enabled: false
4-Command-2: ''

4-Command-3-enabled: false
4-Command-3: ''

4-Command-4-enabled: false
4-Command-4: ''

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#